# Numpy Core

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
# python list Vs numpy (Numerical python) array

l1 = [1,2,3,4,5,6]
print(l1)

import numpy as np
import sys

py_list = [1,2,3,4,5,6]
np_array = np.array([1,2,3,4,5,6])

print(type(py_list),type(np_array))
print(py_list)
print(np_array)

# A python list stores pointers to seperate objects scattered around memory.

# A numpy array(ndarray) stores the actual values packed together in one continuous block.

[1, 2, 3, 4, 5, 6]
<class 'list'> <class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [3]:
py_list_big = list(range(1000))
np_array_big = np.array(range(1000))

list_container_size = sys.getsizeof(py_list_big)
list_elements_size = sum(sys.getsizeof(x) for x in py_list_big)
total_list_size = list_container_size + list_elements_size

print("List container only:", list_container_size)
print("List elements (boxed ints):", list_elements_size)
print("Total list memory:", total_list_size)
print("NumPy array memory (nbytes):", np_array_big.nbytes)

List container only: 8056
List elements (boxed ints): 28000
Total list memory: 36056
NumPy array memory (nbytes): 8000


# List 

In [4]:
# List - we can store heterogenous data

# Numpy array - forces the datatype on all values, converts everything to one common datatype
# where it expands the smaller value to the bigger datatype size and makes it uniform.

print(np.array([1, 2, 3]).dtype)
a = np.array([1,2,3.0])
print(a)
print(np.array([1,2,3.0]).dtype)
print(np.array([1,2,True]).dtype)
print(np.array([1,2,True]))
print(np.array([1,2,"Three"]).dtype)
print(np.array([1,2,"Three"]))
print(np.array(["1",2,None]).dtype)

# bool->int->float->complex
# None datatype -> object
# None cannot be safely represented as a number or string so numpy falls back to generic object type.

int64
[1. 2. 3.]
float64
int64
[1 2 1]
<U21
['1' '2' 'Three']
object


# Array creation

In [5]:
# np.array - converts any existing data into an array

a = np.array([1,2,3])
print(a)
print(a.shape)

b = np.array([[1,2,3],[4,5,6]])  # 2 dimension array
print(b)
print(b.shape) # 2 rows, 3 columns

c = np.array([[1,2,3,5],[4,5,6,5],[1,2,2,5]])
print(c)
print(c.shape)

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3 5]
 [4 5 6 5]
 [1 2 2 5]]
(3, 4)


In [6]:
# np.zeros - creates an array pre-filled with zeroes
# by default datatype is set to float

a = np.zeros(5)  # creates a 1D array filled with 5 zeroes
print(a)

b = np.zeros((2,3))  # creates a 2D array filled with zeroes in 2 rows, 3 columns
print(b)

# This is used to pre-allocate space that you can fill later 

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# np.ones() - create an array filled with ones

c = np.ones(5)
print(c)

d = np.ones((2,3))
print(d)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# np.arange - creates an array of range()
# arange(start,stop,step)

r1 = np.arange(10)
print(r1)

r2 = np.arange(2,10,2)
print(r2)

r3 = np.arange(0,1,0.25)  # decimal values are accepted in step in arange() but not in range()
print(r3)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]
[0.   0.25 0.5  0.75]


In [45]:
# shape manipulation

b = np.arange(0,12)
print(b)

print(b.reshape(3,4))

c = np.array([[1,2],[3,4]])
print(c)
print(c.T)  # transpose -rows to columns and columns to rows
print(c.flatten())  # collapses any rows back to 1D

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3 4]


In [9]:
# linspace()  -  creates an array with evenly spaced values
# linspace(start,stop,count)

l1 = np.linspace(0,10,5)
print(l1)

l2 = np.linspace(0,1,4)
print(l2)

[ 0.   2.5  5.   7.5 10. ]
[0.         0.33333333 0.66666667 1.        ]


In [10]:
# Broadcasting - math operations on array of different shapes

# Broadcasting is numpy's rule syatem for applying math between arrays of different shapes

# scalar + array 

arr = np.array([1,2,3,4])
print(arr+10)  # 10 gets broadcast (stretched across every element automatically)

[1,2,3,4]  + [10,10,10,10] # -> this is called broadcasting

# same shape (1D + 1D)

arr1 = np.array([2,3,4,5])
arr2 = np.array([20,10,10,20])
print(arr1 + arr2)

# 2D + 1D

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
row = np.array([10,20,30])
print(matrix + row)

# 2D array + column
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
col = np.array([[10],[20],[30]])
print(col)

print(matrix + col)

[11 12 13 14]
[22 13 14 25]
[[11 22 33]
 [14 25 36]
 [17 28 39]]
[[10]
 [20]
 [30]]
[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [11]:
# When broadcasting fails - incompatible shapes

try:
    bad = np.array([1,2,3]) + np.array([1,2])
except ValueError as e:
    print("Error", e)

Error operands could not be broadcast together with shapes (3,) (2,) 


# Vectorization

In [12]:
# Vectorization means applying an operation to entire array at once. 
# Instead of writing a loop that touches one element at a time.

import time

size = 1_000_000
py_list = list(range(size))
np_arr = np.arange(size)

start = time.time()
result_loop = [x * 2 for x in py_list]
loop_time = time.time() - start

start = time.time()
result_vec = np_arr * 2
vec_time = time.time() - start

print(f"Loop time: {loop_time:.4f}s")
print(f"Vectorized time: {vec_time:.4f}s")
print(f"Speedup: {loop_time/vec_time:.1f}x")

Loop time: 0.0908s
Vectorized time: 0.0041s
Speedup: 22.1x


| Approach              | What's happening under the hood                         |
|---------------------------|--------------------------------------------------------------|
| [x*2 for x in py_list]        | Python interprets and executes the multiplication ONE item at a time |
| np_arr * 2                      | NumPy applies the multiplication to the WHOLE array in one compiled operation |

In [30]:
# Vectorization 
# using arithmetic operators

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)


# vectorized comparisions

scores = np.array([45,62,78,92,33,88])
print(scores >= 60)


# Boolean masking -  to filter the data using the true or false outputs during comparision

passing = scores[scores >= 60]
print(passing)


# Boolean masking with & and |

ages = np.array([15,18,22,56,47,34,10,25])
print(ages[(ages>=18) & (ages<60)])
print(ages[(ages>18) | (ages<60)])


# Vectorized if/else applied to whole array
# np.where()
# syntax -  np.where(condition, "value if true", "value if false")

labels = np.where(scores >= 60, "Pass", "Fail" )
print(labels)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[     10     400   27000 2560000]
[0 0 0 0]
[False  True  True  True False  True]
[62 78 92 88]
[18 22 56 47 34 25]
[15 18 22 56 47 34 10 25]
['Fail' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass']


# Universal Functions

In [14]:
# universal functions - math functions applied element wise

values = np.array([1,2,4,9,16,25])
print(np.sqrt(values))
print(np.log(values))
print(np.exp(np.array([0,1,2])))  # e raised to the power of/ e=euler's number


# aggregate functions
print(values.sum())
print(values.mean())
print(values.max())
print(values.min())
print(values.std())

[1.         1.41421356 2.         3.         4.         5.        ]
[0.         0.69314718 1.38629436 2.19722458 2.77258872 3.21887582]
[1.         2.71828183 7.3890561 ]
57
9.5
25
1
8.578072821638514


In [15]:
# Vectorized condition counting

readings = np.array([88,-1,92,-1,76,95,-1])
valid_count = (readings != -1).sum()
print(valid_count)

# Custom function to vectorize
# np.vectorize()

def classify(x):
    if x>50:
        return "High"
    else:
        return "Low" 
classify_vec = np.vectorize(classify)
nums = np.array([10,60,30,80])
print(classify_vec(nums))

# np.vectorize lets us apply a regular python function to a whole array in one call.
# note - > np.vectorize is not truly a real vectorize function that will save the time with 
# respect to speed internally it is still looping over every value which does not save us any time.

4
['Low' 'High' 'Low' 'High']


In [16]:
# problem 1
# create a 1D array of the numbers 0 to 20. stepping by 5 using np.arange()

num = np.arange(0,20,5)
print(num)

# create a evenly spaced array of 6 numbers between 0 and 5
print(np.linspace(0,5,6))

# create a 3x4 array of zeroes. print its shape
arr = np.zeros((3,4))
print(arr.shape)
print(arr)

[ 0  5 10 15]
[0. 1. 2. 3. 4. 5.]
(3, 4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
# array creation
# np.eye - to create identity matrix

import numpy as np
print(np.eye(3))
print(np.eye(2))

# np.full - to fill the shape with any number

print(np.full((2,2),7))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]
[[7 7]
 [7 7]]


In [33]:
# astype - to force a datatype

numbers = np.array([3.4,3,4.7,9.8,6.7])
print(numbers.astype(int))

            # OR
            
numbers = np.array([3.4,3,4.7,9.8,6.7]).astype(int)
print(numbers)

[3 3 4 9 6]
[3 3 4 9 6]


In [42]:
# np.unique -  to get the unique values

print(np.unique(numbers))

# np.clip() - setting both upper limit and lower limit
a = np.array([-5,10,45,22,60])
print(np.clip(a,0,40))

# np.random - random float values

print(np.random.rand(3))

# np.random.randint - random integer values
# syntax - np.random.randint(low,high,size)

print(np.random.randint(1,10,size=5))

[3 4 6 9]
[ 0 10 40 22 40]
[0.22856287 0.5481585  0.55181744]
[4 4 4 1 4]


In [48]:
# combining arrays 

a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate([a,b]))
print(np.stack([a,b]))
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [50]:
# splitting - breaks one array into N equal peices, returned as a list of arrays

c = np.arange(9)
print(c)
print(np.split(c,3))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [52]:
# running totals and sorting

sales = np.array([100,150,80,200])
print(np.cumsum(sales))

print(np.diff(sales))

[100 250 330 530]
[ 50 -70 120]
