# Numpy Core

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [6]:
# python list Vs numpy (Numerical python) array

l1 = [1,2,3,4,5,6]
print(l1)

import numpy as np
import sys

py_list = [1,2,3,4,5,6]
np_array = np.array([1,2,3,4,5,6])

print(type(py_list),type(np_array))
print(py_list)
print(np_array)

# A python list stores pointers to seperate objects scattered around memory.

# A numpy array(ndarray) stores the actual values packed together in one continuous block.

[1, 2, 3, 4, 5, 6]
<class 'list'> <class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [7]:
py_list_big = list(range(1000))
np_array_big = np.array(range(1000))

list_container_size = sys.getsizeof(py_list_big)
list_elements_size = sum(sys.getsizeof(x) for x in py_list_big)
total_list_size = list_container_size + list_elements_size

print("List container only:", list_container_size)
print("List elements (boxed ints):", list_elements_size)
print("Total list memory:", total_list_size)
print("NumPy array memory (nbytes):", np_array_big.nbytes)

List container only: 8056
List elements (boxed ints): 28000
Total list memory: 36056
NumPy array memory (nbytes): 8000


# List 

In [15]:
# List - we can store heterogenous data

# Numpy array - forces the datatype on all values, converts everything to one common datatype
# where it expands the smaller value to the bigger datatype size and makes it uniform.

print(np.array([1, 2, 3]).dtype)
a = np.array([1,2,3.0])
print(a)
print(np.array([1,2,3.0]).dtype)
print(np.array([1,2,True]).dtype)
print(np.array([1,2,True]))
print(np.array([1,2,"Three"]).dtype)
print(np.array([1,2,"Three"]))
print(np.array(["1",2,None]).dtype)

# bool->int->float->complex
# None datatype -> object
# None cannot be safely represented as a number or string so numpy falls back to generic object type.

int64
[1. 2. 3.]
float64
int64
[1 2 1]
<U21
['1' '2' 'Three']
object


# Array creation

In [20]:
# np.array - converts any existing data into an array

a = np.array([1,2,3])
print(a)
print(a.shape)

b = np.array([[1,2,3],[4,5,6]])  # 2 dimension array
print(b)
print(b.shape) # 2 rows, 3 columns

c = np.array([[1,2,3,5],[4,5,6,5],[1,2,2,5]])
print(c)
print(c.shape)

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3 5]
 [4 5 6 5]
 [1 2 2 5]]
(3, 4)


In [ ]:
# np.zeros - creates an array pre-filled with zeroes
# by default datatype is set to float

a = np.zeros(5)  # creates a 1D array filled with 5 zeroes
print(a)

b = np.zeros((2,3))  # creates a 2D array filled with zeroes in 2 rows, 3 columns
print(b)

# This is used to pre-allocate space that you can fill later 

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# np.ones() - create an array filled with ones

c = np.ones(5)
print(c)

d = np.ones((2,3))
print(d)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
